# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - staging

pool: monasha-m3

variables:
  - group: Staging

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'staging-upload-keystore.jks'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'nashcrate-stg-cloud-console-service-account.json'

  - script: fastlane staging
    workingDirectory: android/
    displayName: "[staging] Build and release android"

  # - task: CopyFiles@2
  #   inputs:
  #     SourceFolder: 'build/app/outputs/flutter-apk'
  #     Contents: '*.apk'
  #     TargetFolder: '$(build.artifactStagingDirectory)/apk/staging'
  #     OverWrite: true
  #     flattenFolders: true

  # - task: PublishBuildArtifacts@1